# NumPy

Hey guys, welcome to my numpy tutorial.

In [3]:
import numpy as np
a = np.arange(15).reshape(3, 5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [4]:
dict(
    shape=a.shape,
    ndim=a.ndim,
    dtype_name=a.dtype.name,
    itemsize=a.itemsize,
    size=a.size
)

{'shape': (3, 5), 'ndim': 2, 'dtype_name': 'int64', 'itemsize': 8, 'size': 15}

In [5]:
type(a.shape)

tuple

## Operations

Element-wise product:

In [6]:
c = np.array([[1, 2],
              [3, 4]])
d = np.array([[5, 6],
              [7, 8]])

c * d

array([[ 5, 12],
       [21, 32]])

Proper matrix multiplication:

In [10]:
e = np.array([[1, 2],
              [3, 4],
              [5, 6]])
f = np.array([[7, 8],
              [9,10]])

e @ f

# This also works:
e.dot(f)

# This won't work:
# >>> f @ e
# 
# For matrix multiplication to work, left hand width must be equal to
# right hand height.
# >>> (e.shape, f.shape)
# ((3, 2), (2, 2)) # OK: 2 == 2
#
# >>> (f.shape, e.shape)
# ((2, 2), (3, 2)) # Not OK: 2 != 3

array([[ 25,  28],
       [ 57,  64],
       [ 89, 100]])

Also we can add/subtract scalars.

In [14]:
(c * d) - 14

array([[-9, -2],
       [ 7, 18]])

Now look at this:

In [15]:
((c * d) - 14) > 0

array([[False, False],
       [ True,  True]])

In [14]:
g = e.dot(f)
g

array([[ 25,  28],
       [ 57,  64],
       [ 89, 100]])

## Random number generation

In [113]:
from numpy.random import random

h = random((30, 4, 30, 4))

h

array([[[[6.92871147e-01, 6.48960750e-01, 9.10474629e-01,
          4.41744486e-01],
         [1.49396496e-01, 1.09199119e-01, 8.58067671e-01,
          1.51461525e-01],
         [7.53178725e-01, 7.12933323e-01, 6.25682756e-01,
          8.59175972e-01],
         ...,
         [9.67924653e-01, 1.27576526e-01, 5.63422094e-01,
          1.72923633e-01],
         [3.63910718e-01, 1.30953155e-01, 8.68367834e-01,
          9.54939210e-01],
         [2.80168077e-01, 2.75809192e-01, 3.77950310e-01,
          4.97016335e-01]],

        [[7.06142592e-01, 6.86944645e-01, 9.02055209e-01,
          1.11676113e-01],
         [4.43864034e-01, 4.94306884e-03, 5.93771005e-01,
          3.03331123e-01],
         [7.01411122e-01, 2.13214831e-01, 7.35597186e-01,
          2.54618926e-01],
         ...,
         [3.94205543e-01, 4.14154634e-01, 7.29812623e-01,
          1.41065356e-01],
         [7.12229545e-01, 9.35149097e-01, 4.38752218e-01,
          8.36877406e-01],
         [5.81089642e-01, 8.3007324

In [114]:
h.sum()

np.float64(7178.061723230739)

## Exploring dependencies

In [116]:
pip show numpy | grep '^Name:'

Name: numpy
Name: lapack-lite
Name: dragon4
Name: libdivide
Name: Meson
Name: spin
Name: OpenBLAS
Name: LAPACK
Name: GCC runtime library
Name: libquadmath
Note: you may need to restart the kernel to use updated packages.


In [117]:
pip show scipy | grep '^Name:'

Name: scipy
Name: OpenBLAS
Name: LAPACK
Name: GCC runtime library
Name: libquadmath
Note: you may need to restart the kernel to use updated packages.


In [119]:
pip show pandas | grep '^Name:'

Name: pandas
Note: you may need to restart the kernel to use updated packages.


In [121]:
pip show torch | grep '^Name:'

Note: you may need to restart the kernel to use updated packages.


In [2]:
words = 80_000
years = 3
days = 365 * years

words / days

73.05936073059361

In [ ]:
len("""
Let's write a text that's 73 words long and see if that's a lot.
14 words isn't nearly enough for my ambytious begginings! Let's do 28.
25 didn't hit it. Too bad. Anyway, I wonder how many words I should write
now. Okay, just 39, I'm halfway done. I will type three lines and maybe
a little bit more than that and it's my daily writing norm. Which I do
fulfill in my personal writing. Three more words!
""".split(' '))

# I want to extract plain text from what is generated by a .tex file when it's typeset.
# Then I want to be able to count the lenght of that text.

73